const { DataTypes } = require("sequelize");
const template = [
  { prop: "f2", label: "最新价" },
  { prop: "f3", label: "涨跌幅" },
  { prop: "f4", label: "涨跌额" },
  { prop: "f5", label: "总手" },
  { prop: "f6", label: "成交额" },
  { prop: "f7", label: "振幅" },
  { prop: "f8", label: "换手率" },
  { prop: "f9", label: "市盈率" },
  { prop: "f10", label: "量比" },
  { prop: "f11", label: "5分钟涨跌幅" },
  { prop: "f12", label: "股票代码" },
  { prop: "f13", label: "市场" },
  { prop: "f14", label: "股票名称" },
  { prop: "f15", label: "最高价" },
  { prop: "f16", label: "最低价" },
  { prop: "f17", label: "开盘价" },
  { prop: "f18", label: "昨收" },
  { prop: "f20", label: "总市值" },
  { prop: "f21", label: "流通市值" },
  { prop: "f22", label: "涨速" },
  { prop: "f23", label: "市净率" },
  { prop: "f24", label: "60日涨跌幅" },
  { prop: "f25", label: "年初至今涨跌幅" },
  { prop: "f26", label: "上市日期" },
  { prop: "f28", label: "昨日结算价" },
  { prop: "f30", label: "现手" },
  { prop: "f31", label: "买入价" },
  { prop: "f32", label: "卖出价" },
  { prop: "f33", label: "委比" },
  { prop: "f34", label: "外盘" },
  { prop: "f35", label: "内盘" },
  { prop: "f36", label: "人均持股数" },
  { prop: "f37", label: "净资产收益率(加权)" },
  { prop: "f38", label: "总股本" },
  { prop: "f39", label: "流通股" },
  { prop: "f40", label: "营业收入" },
  { prop: "f41", label: "营业收入同比" },
  { prop: "f42", label: "营业利润" },
  { prop: "f43", label: "投资收益" },
  { prop: "f44", label: "利润总额" },
  { prop: "f45", label: "净利润" },
  { prop: "f46", label: "净利润同比" },
  { prop: "f47", label: "未分配利润" },
  { prop: "f48", label: "每股未分配利润" },
  { prop: "f49", label: "毛利率" },
  { prop: "f50", label: "总资产" },
  { prop: "f51", label: "流动资产" },
  { prop: "f52", label: "固定资产" },
  { prop: "f53", label: "无形资产" },
  { prop: "f54", label: "总负债" },
  { prop: "f55", label: "流动负债" },
  { prop: "f56", label: "长期负债" },
  { prop: "f57", label: "资产负债比率" },
  { prop: "f58", label: "股东权益" },
  { prop: "f59", label: "股东权益比" },
  { prop: "f60", label: "公积金" },
  { prop: "f61", label: "每股公积金" },
  { prop: "f62", label: "主力净流入" },
  { prop: "f63", label: "集合竞价" },
  { prop: "f64", label: "超大单流入" },
  { prop: "f65", label: "超大单流出" },
  { prop: "f66", label: "超大单净额" },
  { prop: "f69", label: "超大单净占比" },
  { prop: "f70", label: "大单流入" },
  { prop: "f71", label: "大单流出" },
  { prop: "f72", label: "大单净额" },
  { prop: "f75", label: "大单净占比" },
  { prop: "f76", label: "中单流入" },
  { prop: "f77", label: "中单流出" },
  { prop: "f78", label: "中单净额" },
  { prop: "f81", label: "中单净占比" },
  { prop: "f82", label: "小单流入" },
  { prop: "f83", label: "小单流出" },
  { prop: "f84", label: "小单净额" },
  { prop: "f87", label: "小单净占比" },
  { prop: "f88", label: "当日DDX" },
  { prop: "f89", label: "当日DDY" },
  { prop: "f90", label: "当日DDZ" },
  { prop: "f91", label: "5日DDX" },
  { prop: "f92", label: "5日DDY" },
  { prop: "f94", label: "10日DDX" },
  { prop: "f95", label: "10日DDY" },
  { prop: "f97", label: "DDX飘红天数(连续)" },
  { prop: "f98", label: "DDX飘红天数(5日)" },
  { prop: "f99", label: "DDX飘红天数(10日)" },
  { prop: "f100", label: "行业" },
  { prop: "f101", label: "板块领涨股" },
  { prop: "f102", label: "地区板块" },
  { prop: "f103", label: "备注" },
  { prop: "f104", label: "上涨家数" },
  { prop: "f105", label: "下跌家数" },
  { prop: "f106", label: "平家家数" },
  { prop: "f112", label: "每股收益" },
  { prop: "f113", label: "每股净资产" },
  { prop: "f114", label: "市盈率（静）" },
  { prop: "f115", label: "市盈率（TTM）" },
  { prop: "f124", label: "当前交易时间" },
  { prop: "f128", label: "板块领涨股" },
  { prop: "f129", label: "净利润" },
  { prop: "f130", label: "市销率TTM" },
  { prop: "f131", label: "市现率TTM" },
  { prop: "f132", label: "总营业收入TTM" },
  { prop: "f133", label: "股息率" },
  { prop: "f134", label: "行业板块的成分股数" },
  { prop: "f135", label: "净资产" },
  { prop: "f138", label: "净利润TTM" },
  { prop: "f221", label: "更新日期" },
];

const modelKeys = template.map((item) => item.prop);
const modelLabels = template.map((item) => item.label);

exports.modelKeys = modelKeys;
exports.modelLabels = modelLabels;
exports.template = template;

const defineModel = {};
modelKeys.forEach((modelItem) => {
  defineModel[modelItem] = {
    type: DataTypes.STRING,
    allowNull: true,
    defaultValue: "",
  };
});
exports.defineModel = defineModel;
